Repository planme-app/back, pull requests merged in 2023-07, with the labels that each got.

#13 [feat] #12 add check-email
  src/user/dto/checkEmail.dto.ts
  src/user/user.controller.ts
Labels: :sparkles: feat, :technologist: BE

#14 [Feat] #7 get user routine
  .vscode/launch.json
  package-lock.json
  package.json
  src/app.module.ts
  src/main.ts
  src/routine/dto/findRoutinesByDate.dto.ts
  src/routine/repositories/prisma.routine.repository.ts
  src/routine/repositories/prisma.routineInstance.repository.ts
  src/routine/repositories/routinInstance.repository.interface.ts
  src/routine/repositories/routine.repository.interface.ts
  src/routine/routine.controller.ts
  src/routine/routine.entity.ts
  src/routine/routine.module.ts
  src/routine/services/routine.interface.ts
  src/routine/services/routine.service.ts
  src/user/repository/user.repository.ts
  src/user/user.module.ts
Labels: :sparkles: feat, :technologist: BE

#17 [Feat] #8 create user routine
  src/routine/dto/createRoutine.dto.ts
  src/routine/repositories/prisma.routine.repository.ts
  src/routine/repositories/prisma.routineInstance.repository.ts
  src/routine/repositories/routinInstance.repository.interface.ts
  src/routine/repositories/routine.repository.interface.ts
  src/routine/routine.controller.ts
  src/routine/routine.module.ts
  src/routine/services/routine.interface.ts
  src/routine/services/routine.service.ts
  src/user/service/user.service.ts
  src/user/user.module.ts
Labels: :sparkles: feat, :technologist: BE

#18 [Feat] #15 add jwt
  package-lock.json
  package.json
  src/routine/routine.controller.ts
  src/user/get-user.decorator.ts
  src/user/jwt.strategy.ts
  src/user/service/user.interface.ts
  src/user/service/user.service.ts
  src/user/user.controller.ts
  src/user/user.entity.ts
  src/user/user.module.ts
Labels: :sparkles: feat, :technologist: BE

#23 [feat] #19 create routine template
  package-lock.json
  package.json
  src/app.module.ts
  src/template/dto/createTemplate.dto.ts
  src/template/repository/template.interface.ts
  src/template/repository/template.repository.ts
  src/template/service/template.interface.ts
  src/template/service/template.service.ts
  src/template/template.controller.ts
  src/template/template.entity.ts
  src/template/template.module.ts
Labels: :sparkles: feat, :technologist: BE

#25 [feat] #20 update routine template
  src/template/dto/updateTemplate.dto.ts
  src/template/repository/template.interface.ts
  src/template/repository/template.repository.ts
  src/template/service/template.interface.ts
  src/template/service/template.service.ts
  src/template/template.controller.ts
Labels: :sparkles: feat, :technologist: BE

#27 [Feat] #26 get routine template by Id
  src/template/service/template.interface.ts
  src/template/service/template.service.ts
  src/template/template.controller.ts
Labels: :sparkles: feat, :technologist: BE

#28 [Feat] #22 delete routine template
  src/template/repository/template.interface.ts
  src/template/repository/template.repository.ts
  src/template/service/template.interface.ts
  src/template/service/template.service.ts
  src/template/template.controller.ts
Labels: :sparkles: feat, :technologist: BE

#31 [feat] #30 split user and auth
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.entity.ts
  src/auth/auth.module.ts
  src/auth/dto/checkEmail.dto.ts
  src/auth/dto/signin.dto.ts
  src/auth/dto/signup.dto.ts
  src/auth/jwt.strategy.ts
  src/auth/service/auth.interface.ts
  src/auth/service/auth.service.ts
  src/routine/routine.module.ts
  src/template/template.module.ts
  src/user/dto/create-user.dto.ts
  src/user/dto/update-user.dto.ts
  src/user/repository/user.interface.ts
  src/user/repository/user.repository.ts
  src/user/service/user.interface.ts
  src/user/service/user.service.ts
  src/user/user.controller.ts
  src/user/user.entity.ts
  src/user/user.module.ts
Labels: :technologist: BE, :recycle: refactor

#33 [feat] #32 add routine template id dto
  src/template/dto/routineTemplateId.dto.ts
  src/template/service/template.interface.ts
  src/template/service/template.service.ts
  src/template/template.controller.ts
Labels: :bug: bug, :sparkles: feat, :technologist: BE

#34 [Feat] #11 edit routine api
  src/routine/dto/editRoutine.dto.ts
  src/routine/repositories/prisma.routine.repository.ts
  src/routine/repositories/prisma.routineInstance.repository.ts
  src/routine/repositories/routine.repository.interface.ts
  src/routine/routine.controller.ts
  src/routine/services/routine.interface.ts
  src/routine/services/routine.service.ts
Labels: :sparkles: feat, :technologist: BE

#35 [Feat] #10 delete routine api
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/service/auth.service.ts
  src/routine/dto/deleteRoutine.dto.ts
  src/routine/repositories/prisma.routine.repository.ts
  src/routine/repositories/routine.repository.interface.ts
  src/routine/routine.controller.ts
  src/routine/routine.module.ts
  src/routine/services/routine.interface.ts
  src/routine/services/routine.service.ts
  src/template/repository/template.repository.ts
  src/template/template.module.ts
Labels: :sparkles: feat, :technologist: BE

#37 [Feat] #36 routine batch
  package-lock.json
  package.json
  src/app.module.ts
  src/batch/batch.module.ts
  src/batch/batch.service.ts
  src/routine/repositories/prisma.routineInstance.repository.ts
  src/routine/routine.module.ts
  src/routine/services/routine.service.ts
  src/user/user.module.ts
Labels: :sparkles: feat, :technologist: BE

#39 [feat] #38 add enableCors
  src/main.ts
Labels: :sparkles: feat, :technologist: BE

#41 [fix] #40 duplicate creation of routine_instances
  src/batch/batch.service.ts
  src/routine/repositories/prisma.routineInstance.repository.ts
Labels: :bug: bug, :technologist: BE
